#指明端口号信息
server:
  port: 80
#注册中心上显示的别名为
spring:
  application:
    name: service-zuul
#zuul也需要注册至注册中心上
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/

#配置反向代理
zuul:
  #路由
  routes:
    api-a:
     ### 以 /api-member/访问转发到会员服务
      path: /api-member/**
      serviceId: app-bunana-member
    api-b:
        ### 以 /api-order/访问转发到订单服务
      path: /api-order/**
      serviceId: app-bunana-order