###服务启动端口号
server:
  port: 8000
###服务名称(服务注册到eureka名称)  
spring:
    application:
        name: app-bunana-member
###服务注册到eureka地址
eureka:
  client:
    service-url:
           defaultZone: http://localhost:10000/eureka

           
###因为该应用是各项服务，需要将自己上报注册至eureka中
    register-with-eureka: true
###需要检索服务
    fetch-registry: true
    #表示eureka client间隔多久去拉取服务注册信息，默认30秒(服务每30秒拉取信息保存本地jvm)
    registry-fetch-interval-seconds: 30
    
# 心跳检测检测与续约时间
# 测试时将值设置设置小些，保证服务关闭后注册中心能及时踢出服务
  instance:
#表示eureka client发送心跳给server端的频率。
#如果在leaseExpirationDurationInSeconds后，server端没有收到client的心跳，则将摘除该instance。
#除此之外，如果该instance实现了HealthCheckCallback，并决定让自己unavailable的话，则该instance也不会接收到流量。
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）
    lease-renewal-interval-in-seconds: 1
#表示eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则将移除该instance。
    lease-expiration-duration-in-seconds: 2 